export const prods = [
    {
        product: "Sarasa",
        description: "Sarasa descriptiva con varias palabras. Sarasa descriptiva con varias palabras. Sarasa descriptiva con varias palabras. ",
        type: "Sarasa cósmica",
        image: "https://bit.ly/2Z4KKcF",
    },
    {
        product: "Sarasa",
        description: "Sarasa descriptiva con varias palabras",
        type: "Sarasa cósmica",
        image: "https://bit.ly/2Z4KKcF",
    },
    {
        product: "Sarasa",
        description: "Sarasa descriptiva con varias palabras",
        type: "Sarasa cósmica",
        image: "https://bit.ly/2Z4KKcF",
    },
    {
        product: "Sarasa",
        description: "Sarasa descriptiva con varias palabras. Sarasa descriptiva con varias palabras. Sarasa descriptiva con varias palabras. ",
        type: "Sarasa cósmica",
        image: "https://bit.ly/2Z4KKcF",
    },
    {
        product: "Sarasa",
        description: "Sarasa descriptiva con varias palabras",
        type: "Sarasa cósmica",
        image: "https://bit.ly/2Z4KKcF",
    },
    {
        product: "Sarasa",
        description: "Sarasa descriptiva con varias palabras",
        type: "Sarasa cósmica",
        image: "https://bit.ly/2Z4KKcF",
    },
    {
        product: "Sarasa",
        description: "Sarasa descriptiva con varias palabras",
        type: "Sarasa cósmica",
        image: "https://bit.ly/2Z4KKcF",
    },
    {
        product: "Sarasa",
        description: "Sarasa descriptiva con varias palabras",
        type: "Sarasa cósmica",
        image: "https://bit.ly/2Z4KKcF",
    },
    {
        product: "Sarasa",
        description: "Sarasa descriptiva con varias palabras",
        type: "Sarasa cósmica",
        image: "https://bit.ly/2Z4KKcF",
    },
    {
        product: "Sarasa",
        description: "Sarasa descriptiva con varias palabras",
        type: "Sarasa cósmica",
        image: "https://bit.ly/2Z4KKcF",
    },
    {
        product: "Sarasa",
        description: "Sarasa descriptiva con varias palabras",
        type: "Sarasa cósmica",
        image: "https://bit.ly/2Z4KKcF",
    },
    {
        product: "Sarasa",
        description: "Sarasa descriptiva con varias palabras",
        type: "Sarasa cósmica",
        image: "https://bit.ly/2Z4KKcF",
    },
    {
        product: "Sarasa",
        description: "Sarasa descriptiva con varias palabras",
        type: "Sarasa cósmica",
        image: "https://bit.ly/2Z4KKcF",
    },
    {
        product: "Sarasa",
        description: "Sarasa descriptiva con varias palabras",
        type: "Sarasa cósmica",
        image: "https://bit.ly/2Z4KKcF",
    },
    {
        product: "Sarasa",
        description: "Sarasa descriptiva con varias palabras",
        type: "Sarasa cósmica",
        image: "https://bit.ly/2Z4KKcF",
    },
    {
        product: "Sarasa",
        description: "Sarasa descriptiva con varias palabras",
        type: "Sarasa cósmica",
        image: "https://bit.ly/2Z4KKcF",
    },
    {
        product: "Sarasa",
        description: "Sarasa descriptiva con varias palabras",
        type: "Sarasa cósmica",
        image: "https://bit.ly/2Z4KKcF",
    },
    {
        product: "Sarasa",
        description: "Sarasa descriptiva con varias palabras",
        type: "Sarasa cósmica",
        image: "https://bit.ly/2Z4KKcF",
    },
    {
        product: "Sarasa",
        description: "Sarasa descriptiva con varias palabras",
        type: "Sarasa cósmica",
        image: "https://bit.ly/2Z4KKcF",
    },
    {
        product: "Sarasa",
        description: "Sarasa descriptiva con varias palabras",
        type: "Sarasa cósmica",
        image: "https://bit.ly/2Z4KKcF",
    },
    {
        product: "Sarasa",
        description: "Sarasa descriptiva con varias palabras",
        type: "Sarasa cósmica",
        image: "https://bit.ly/2Z4KKcF",
    },
]